steps:
  - id: "terraform init"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Executing 'terraform init' on PRD environment..."
        cd environments/prd
        terraform init
  - id: "terraform plan"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Executing 'terraform plan' on PRD environment..."
        cd environments/prd
        terraform plan
  - id: "terraform apply"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Executing 'terraform apply' on PRD environment..."
        cd environments/prd
        terraform apply -auto-approve
options:
  logging: CLOUD_LOGGING_ONLY
